import {
  ArrowLeftOutlined,
  CheckCircleOutlined,
  CloseCircleOutlined,
  DeleteRowOutlined,
  DoubleLeftOutlined,
  DoubleRightOutlined,
  ExclamationCircleOutlined,
  FileExclamationOutlined,
  GlobalOutlined,
  LeftCircleOutlined,
  LoadingOutlined,
  LogoutOutlined,
  MoonOutlined,
  QuestionCircleOutlined,
  ReloadOutlined,
  SunOutlined,
  UserOutlined,
  UsergroupAddOutlined,
  CloseOutlined,
} from "@ant-design/icons";

export {
  ArrowLeftOutlined,
  CheckCircleOutlined,
  CloseCircleOutlined,
  DeleteRowOutlined,
  DoubleLeftOutlined,
  DoubleRightOutlined,
  ExclamationCircleOutlined,
  FileExclamationOutlined,
  GlobalOutlined,
  LeftCircleOutlined,
  LoadingOutlined,
  LogoutOutlined,
  MoonOutlined,
  QuestionCircleOutlined,
  ReloadOutlined,
  SunOutlined,
  UserOutlined,
  UsergroupAddOutlined,
  CloseOutlined,
};
